name: Build and Deploy HateSpeech Detection Model

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # make-unit-tests:
  #   name: Build Model
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code #copy code from repo to runner
  #       uses: actions/checkout@v4 

  #     - name: Set Test environment   #for maven
  #       run: |
  #         pip install -r requirements.txt 
  #         pip install pytest pytest-ordering
  #         pip install torch==2.6.0
          
  #     - name: Unit Tests
  #       run: |
  #         pytest --maxfail=1 --disable-warnings -q tests/
    
  # build-push-training-image:
  #   name: Build and Push Training Image
  #   runs-on: ubuntu-latest
  #   needs: make-unit-tests
  #   steps:
  #     - name: Checkout code 
  #       uses: actions/checkout@v4 

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #         registry: docker.io

  #     - name: Build Training Image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./Dockerfile.train
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hatespeech-detection-training:latest
          
  # build-push-inference-image:
  #   name: Build and Push Inference Image
  #   runs-on: ubuntu-latest
  #   needs: make-unit-tests
  #   steps:
  #     - name: Checkout code #copy code from repo to runner
  #       uses: actions/checkout@v4 

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #         registry: docker.io

  #     - name: Build Inference Image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: inference
  #         dockerfile: Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hatespeech-detection-inference:latest

  deploy:
    name: SSH Deployment
    runs-on: ubuntu-latest
    # needs: [build-push-training-image, build-push-inference-image]
    steps:
      - name: Checkout code #copy code from repo to runner
        uses: actions/checkout@v4 

      - name: SSH to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yml"
          target: "/home/rlabadie/inference-hate-speech"

      - name: Deploy Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/rlabadie/inference-hate-speech
            docker-compose down
            docker-compose pull
            docker-compose up inference -d --build