name: Build and Deploy HateSpeech Detection Model

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #copy code from repo to runner
        uses: actions/checkout@v4 

      - name: Set Test environment   #for maven
        run: |
          pip install -r requirements.txt 
          pip install pytest pytest-ordering
          
      - name: Unit Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q tests/

